export type ProjectDetailGroup = {
  title: string;
  items: string[];
};

export type WorkingProject = {
  name: string;
  sourceDocuments: string[];
  marqueeUSP: string;
  overview?: {
    propertyName?: string;
    location?: string;
    configurations?: string;
  };
  detailGroups: ProjectDetailGroup[];
};

export const workingProjects: WorkingProject[] = [
  {
    name: "Birla Evara",
    sourceDocuments: ["Birla Evara Customer Presentation_Feb 2026.pdf"],
    marqueeUSP: "Birla Evara | Total Indoor Amenities area 58,247 Sq Ft.",
    detailGroups: [
      {
        title: "Location",
        items: [
          "Birla Evara, Sarjapur",
          "5 kms Carmelaram Railway Station",
          "3.5 kms Proposed Carmelaram Metro station (Part of Red line)",
          "15 kms Infosys upcoming HQ (Under construction)",
          "2 kms Proposed STRR",
          "3 kms Proposed PRR",
          "Rapid development, connectivity and proximity to IT hubs",
        ],
      },
      {
        title: "Project Type",
        items: [
          "3BHK UNIT CONFIGURATION & PRICING",
          "4BHK UNIT CONFIGURATION & PRICING",
        ],
      },
      {
        title: "Unit Types",
        items: [
          "3BHK Compact USABLE CARPET AREA 1127 Sqft",
          "3 BHK Regular USABLE CARPET AREA 1275 Sqft",
          "3 BHK + SQ USABLE CARPET AREA 1461 Sqft",
          "4BHK + SQ with Pooja Room USABLE CARPET AREA 1736 Sqft",
          "4BHK + SQ USABLE CARPET AREA 1733 Sqft",
        ],
      },
      {
        title: "Amenities",
        items: [
          "Total Indoor",
          "Amenities area",
          "58,247 Sq Ft.",
          "5,411.3 Sq. M",
          "Amenities below Tower",
          "and Multipurpose Hall",
          "27,445.52 Sq Ft.",
          "2,549.77 Sq M",
          "North Club",
          "Badminton court",
          "Spa",
          "Café",
          "Squash court",
          "Business centre",
          "Mini theatre",
          "14,249.81 Sq Ft. / 1,323.84 Sq M",
          "South Club",
          "Zumba",
          "Aerobic",
          "Yoga",
          "Swimming pool",
          "Kids pool",
          "Jacuzzi",
          "Badminton court",
          "Squash court",
          "Gymnasium",
          "16,551.80 Sq Ft./ 1,537.7 Sq M",
          "Community Street",
          "Children's Play Area.",
          "Community Seating",
          "Tennis Court",
          "Basketball Court",
          "Pet Park",
        ],
      },
      {
        title: "Pricing",
        items: [
          "3 BHK COMPACT 1127 – 1137 (104.70 - 105.63) 1.87 Cr – 1.93 Cr",
          "3 BHK REGULAR 1275 – 1278 (118.45 - 118.73) 2.01 Cr – 2.10 Cr",
          "3 BHK + SQ 1427 - 1461 (132.57 – 135.73) 2.18 Cr – 2.31 Cr",
          "4BHK + SQ 1733 – 1759 (161.0 - 163.42) 2.93 Cr – 3.15 Cr",
          "** Excludes GST, Possession charges and SDR",
        ],
      },
      {
        title: "Other Details",
        items: [
          "3BHK  PAYMENT PLAN (20:20:60)",
          "Booking Amount 10%",
          "Within 90 days of booking 10%",
          "Completion of Superstructure of Tower 20%",
          "On Application of OC 40%",
          "On Receipt of OC/On offer of possession 20%",
          "4BHK PAYMENT PLAN (10:10:80)",
          "Within 1 year from the date of booking 10%",
          "On Receipt of OC 80%",
        ],
      },
    ],
  },
  {
    name: "Nambiar District 25",
    sourceDocuments: ["Nambiar District 25 Phase 2 mini brochure final.pdf"],
    marqueeUSP: "Nambiar District 25 | 7 acre clubhouse.",
    detailGroups: [
      {
        title: "Location",
        items: [
          "Nambiar District 25 is strategically located close to Wipro, Cisco, ITPL, and Electronic City, and a mere 600 meters from the upcoming Red Line Muthanallur Metro Station.",
          "Post 2021, the Sarjapura Road area has seen a boom in demand for luxury housing with property prices approaching a 63% rise.",
          "Luxury meets location at District 25 to offer the perfect living spaces as well as a high-return investment opportunity.",
        ],
      },
      {
        title: "Project Type",
        items: [
          "District 25 is a sprawling, proposed integrated township, whose central highlight is a clubhouse spread over 7 acres.",
          "Fully loaded with an Olympic-length swimming pool, a gym as well as courts for badminton, squash, bowling alley and many more.",
          "The jewel in its crown is the 4km jogging track.",
        ],
      },
      {
        title: "Unit Types",
        items: [
          "3 BED 3T (Small) - UNIT - 1",
          "Sale Area = 157.46 sqm",
          "1695 sft",
          "Carpet area  = 104.46 sqm",
          "1124 sft",
          "Balcony area  = 10.18 sqm",
          "110 sft",
          "3 BED 2T - UNIT - 2",
          "Sale Area = 135.13 sqm",
          "1454 sft",
          "Carpet area  = 89.61 sqm",
          "965 sft",
          "Balcony area  = 8.03 sqm",
          "86 sft",
          "3BED 3T (Large) - UNIT - 1",
          "Sale Area = 190.11 sqm",
          "2046 sft",
          "Carpet area  = 121.04 sqm",
          "1303 sft",
          "Balcony area  = 19.64 sqm",
          "211 sft",
          "3 BED 3T (Medium) - UNIT - 1",
          "Sale Area = 176.16 sqm",
          "1896 sft",
          "Carpet area  = 111.13 sqm",
          "1196 sft",
          "Balcony area  = 18.19 sqm",
          "196 sft",
          "4 BED 5T (Large) UNIT - 2",
          "Sale Area = 278.29 sqm",
          "2995 sft",
          "Carpet area  = 181.87 sqm",
          "1958 sft",
          "Balcony area  = 23.70 sqm",
          "255 sft",
          "4 BED 4T  - UNIT - 1",
          "Sale Area = 237.91 sqm",
          "2561 sft",
          "Carpet area  = 153.17 sqm",
          "1649 sft",
          "Balcony area  = 23.59 sqm",
          "254 sft",
        ],
      },
      {
        title: "Amenities",
        items: [
          "OUTDOOR AMENITIES CLUBHOUSEPHASE 1 & 2",
          "01. Carriage way with cycling lane",
          "18. Swimming pool",
          "24. Pickleball",
          "25. Basketball",
          "26. Volleyball",
          "27. Tennis court",
          "45. Yoga deck",
          "47. Kids’ Play zones",
          "53. SOHO Zone - Flea Market",
          "56. Food Truck zone",
          "61. Projection wall",
          "62. Play area",
          "69. Family pool",
          "70. Olympic length pool",
          "71. Party lawn",
          "74. Water court",
          "Unique amenities like an observatory, indoor pool, a space for creche, spa, restaurant, saloon, grocery store, shops, clinic, café, co-working space, central kitchen, library, Yoga hall, AV room and more",
        ],
      },
      {
        title: "Features",
        items: [
          "Spacious balconies, no shared walls - the ultimate in privacy and comfort. Just 4 units per floor and 4 elevators# in each tower.",
          "Live in a sprawling expanse with 80% open space, 40% green space and 3500+ trees.",
          "Designed with sustainable principles like rainwater harvesting and EV charging points*",
          "Residences with no common walls, sunlit windows with large picturesque balconies and exclusive elevator access.",
        ],
      },
      {
        title: "Area",
        items: [
          "7 acre clubhouse.",
          "the clubhouse is a sprawling 2.5 lakh+ sft space packed with world-class sports, fitness and recreational amenities.",
        ],
      },
    ],
  },
  {
    name: "SSVR Meridian",
    sourceDocuments: ["SSVR_MERIDIAN_BROCHURE.pdf"],
    marqueeUSP: "SSVR Meridian | 119 UNITS",
    detailGroups: [
      {
        title: "Location",
        items: [
          "SY NO: 46/12,46/13,46/16 & 46/17 , Silver Oak Main Road, Panathur Hobli, Varthur, Bengaluru, Karnataka 560087",
          "CLOSE TO EVERYTHING THAT Matters",
          "Strategically located in a fast-developing and well-connected part of the city",
        ],
      },
      {
        title: "Project Type",
        items: [
          "3 B H K L U X U RY A PA R T M E N T S",
          "A thoughtfully envisioned residential community where elegance meets function.",
          "3BHK 3Bedroom + 2Toilet",
          "3BHK 3Bedroom + 3Toilet",
        ],
      },
      {
        title: "Unit Types",
        items: [
          "3BHK Facing : WEST 1600 SQFT",
          "3BHK Facing : NORTH 1500 SQFT",
          "3BHK Facing : NORTH 1430 SQFT",
          "3BHK Facing : NORTH 1615 SQFT",
          "3BHK Facing : EAST 1690 SQFT",
          "3BHK Facing : EAST 1640 SQFT",
          "3BHK Facing : EAST 1475 SQFT",
        ],
      },
      {
        title: "Amenities",
        items: [
          "CHILDREN’S PLAY AREA",
          "SENIOR SEAATING AREA",
          "KIDS’ POOL",
          "SWIMMING POOL",
          "GAZEBO",
          "JOGGING TRACK",
          "CRICKET PRACTICE PITCHES",
          "OUTDOOR CHILDREN’S PLAY AREA",
          "HALF BASKET BALL COURT",
          "OPEN AMPHITHEATRE",
          "CRICKET PRACTICE NET",
          "modern, fully equipped gymnasium",
          "indoor games room",
          "multi-purpose hall",
        ],
      },
      {
        title: "Features",
        items: [
          "119 UNITS",
          "70% Open Space",
          "100% Vastu Compliance",
          "10+ Amenities",
          "Land Parcel 1.22 Acre",
          "Floors G+17",
          "Towers are placed to allow natural light and ventilation.",
        ],
      },
      {
        title: "Proximity",
        items: [
          "close to key IT hubs, prominent schools, reputed hospitals, shopping destinations, and entertainment zones",
          "everything is just a short drive away",
        ],
      },
    ],
  },
  {
    name: "The Sports Province",
    sourceDocuments: ["The Sports Province_A4_Brochure_V7_Jul25.pdf"],
    marqueeUSP: "The Sports Province | 2, 3 & 3.5 BHK homes starting at ₹1.3 Cr*",
    detailGroups: [
      {
        title: "Location",
        items: [
          "The Sports Province with Towers 7, 8 & 9 at The Right Life",
          "RIGHT NEXT TO EVERYTHING",
          "Just 800m from upcoming Dommasandra metro station",
        ],
      },
      {
        title: "Project Type",
        items: ["Residential. Retail. Commercial. Sports."],
      },
      {
        title: "Unit Types",
        items: ["2, 3 & 3.5 BHK homes starting at ₹1.3 Cr*"],
      },
      {
        title: "Amenities",
        items: [
          "World-class Cricket Nets",
          "FIFA-standard Football Ground",
          "Olympic-inspired Skating Park",
          "Futsal Court",
          "FIBA-standard Basketball Court",
          "ITF-approved Tennis Court",
          "ITF-approved Padel Court",
          "ITF-approved Pickleball Court",
          "BWF-approved Badminton Court",
          "BWF-approved Squash Court",
          "Temperature-controlled Half Olympic-size Swimming Pool",
          "Golf Putting Area",
          "Tranquil Yoga & Aerial Yoga Studios",
        ],
      },
      {
        title: "Features",
        items: [
          "Just a short walk to daily sport, not a weekend drive",
          "Everyday fitness for every age and interest",
          "A safe, green environment where children can be independent and make new friends",
        ],
      },
      {
        title: "Area",
        items: [
          "100+ acre community with 84% open space",
          "3.5 lakh SFT of clubhouses for downtime and discovery",
        ],
      },
      {
        title: "Pricing",
        items: [
          "Attractive pre-EMI plan from Godrej Capital & Bajaj Housing Finance starting at ₹9,999*/month",
          "2, 3 & 3.5 BHK homes starting at ₹1.3 Cr*",
        ],
      },
      {
        title: "Other Details",
        items: [
          "PRM/KA/RERA/1251/308/PR/280324/006766",
          "PRM/KA/RERA/1251/308/PR/210325/007611",
        ],
      },
    ],
  },
  {
    name: "MEDA East Winds",
    sourceDocuments: ["Meda_Sales_Presenter_Aug25.pdf", "Meda Floor Plan.pdf"],
    marqueeUSP: "MEDA East Winds | 8.25 acres",
    detailGroups: [
      {
        title: "Location",
        items: [
          "Located in Panathur, MEDA East Winds keeps you close to schools, tech parks, healthcare, and dining - with the upcoming metro just minutes away.",
          "Bangalore Address: Meda East Winds, Sy.No. 12/1/2/3, Opp. Prakruthi Enclave, Panathur, Bangalore - 560103",
        ],
      },
      {
        title: "Project Type",
        items: [
          "East Bangalore’s Most Thoughtfully Designed Community",
          "Where Life Opens Up to Space, Light, and Calm.",
        ],
      },
      {
        title: "Unit Types",
        items: [
          "2, 3, 3.5 & 4.5 BHKs",
          "WEST 2BHK 1378 SFT",
          "NORTH 2BHK 1362 SFT",
          "NORTH 2BHK 1386 SFT",
          "NORTH 1BHK 728 SFT",
          "SOUTH 1BHK 638 SFT",
          "SOUTH 1BHK 643 SFT",
          "WEST 4BHK 2463 SFT",
          "EAST 4BHK 2502 SFT",
          "EAST 3BHK 2004 SFT",
          "WEST 3BHK 1910 SFT",
          "WEST 3BHK 1905 SFT",
          "NORTH 3BHK 1584 SFT",
          "NORTH 3BHK 1518 SFT",
        ],
      },
      {
        title: "Amenities",
        items: [
          "40+ amenities",
          "22,000+ sq. ft. clubhouse",
          "Cricket Pitch",
          "Half Basketball Court",
          "Pickleball Court",
          "Miyawaki Forest",
          "Nature Walk With Water Feature",
          "Yoga Lawn",
          "Zen Garden",
          "Jogging Track",
          "Outdoor Gym",
          "Amphitheatre",
          "Skating Rink",
          "Children’s Play Area",
          "Gaming Zone",
          "Pet Park",
          "Badminton Court",
          "Tennis Court",
          "Rooftop Pool with Deck",
          "Co-working Space",
          "Party Hall",
          "Guest Rooms",
        ],
      },
      {
        title: "Proximity",
        items: [
          "Prestige Tech Park : 2.2 km",
          "Embassy Tech Village : 2.3 km",
          "Global Technology Center : 4.1 km",
          "Belenus Champion Hospital : 6.5 km",
          "Manipal Hospital : 7.7 km",
          "New Horizon Gurukul School : 2 km",
          "Orchids The Intl. School : 1 km",
          "Vibgyor Rise School : 1.3 km",
          "Forum Value Mall : 6.7 km",
          "Phoenix Market City : 10 km",
        ],
      },
      {
        title: "Area",
        items: [
          "8.25 acres",
          "75% open space",
          "542 units",
          "48,000 sq. ft. central spine",
        ],
      },
    ],
  },
  {
    name: "East Park Residences (Ramsons Trendsquares)",
    sourceDocuments: ["Ramsons Brochure New launch.pdf"],
    marqueeUSP: "East Park Residences | 20 percent ground coverage, leaving 80 percent open areas",
    detailGroups: [
      {
        title: "Location",
        items: [
          "Located on Sarjapur Road",
          "Nestled along the enchanting Sarjapur Road",
          "close proximity to renowned institutions and upscale shopping destinations",
        ],
      },
      {
        title: "Project Type",
        items: [
          "RESIDENTIAL I RETAIL I OFFICE I HOSPITALITY",
          "Experience our new Towers E and F",
          "TOWER A,B,C & D SOLD OUT",
        ],
      },
      {
        title: "Unit Types",
        items: [
          "4 Bed 'Presidential Suites'",
          "3.5 Bed'Executive Suites'",
          "3 Bed 'Royal Suites'",
          "3BHK-3T-TYPE1",
          "SuperBuilt-upArea",
          "156.84",
          "1688.23",
          "RERA Carpet Area",
          "106.27",
          "1143.89",
          "Balcony Area",
          "8.74",
          "94.08",
          "3.5 BHK-3T",
          "Super Built-up Area",
          "182.59",
          "1965.45",
          "RERA Carpet Area",
          "118.55",
          "1276.07",
          "Balcony Area",
          "16.69",
          "179.65",
          "4 BHK-4T",
          "Super Built-up Area",
          "221.42",
          "2383.35",
          "RERA Carpet Area",
          "148.82",
          "1601.90",
          "Balcony Area",
          "16.66",
          "179.33",
          "3 BHK-3T-TYPE 3",
          "SuperBuilt-up Area",
          "155.58",
          "1674.70",
          "RERACarpetArea",
          "103.60",
          "1115.15",
          "Balcony Area",
          "11.60",
          "124.86",
        ],
      },
      {
        title: "Amenities",
        items: [
          "Co-working space",
          "Golf simulator and putting range",
          "Gaming arena",
          "Banquet hall",
          "Party hall",
          "Gym",
          "Yoga room",
          "AV room",
          "Spa/salon",
          "Library",
          "Billiards room",
          "Table tennis room",
          "Squash court",
          "Badminton court",
          "Creche",
          "Guest rooms",
          "Swimming Pools",
          "Tennis Court",
          "Skating Rink",
          "Children's Playground",
          "Dog Park",
          "Open Air Theatre",
        ],
      },
      {
        title: "Features",
        items: [
          "Sixtowers rise elegantly on 6.5 acres",
          "20 percent ground coverage, leaving 80 percent open areas",
          "With 30,000 sq. ft. of meticulously designed parks, open spaces and stunning buildings",
          "Edge-to-edge windows",
          "Privacy in every detail",
          "Vastu-compliance",
          "TWIN CLUBHOUSES",
        ],
      },
      {
        title: "Proximity",
        items: [
          "WIPRO KODATHI/CORPORATE OFFICE",
          "RGA TECH PARK",
          "RMZ ECOWORLD",
          "EMBASSY TECH VILLAGE",
          "OAKRIDGE SCHOOL",
          "DELHI PUBLIC SCHOOL EAST",
          "MANIPAL HOSPITAL",
          "MOTHERHOOD HOSPITAL",
          "SAKRA WORLD HOSPITAL",
        ],
      },
    ],
  },
  {
    name: "TRL (The Right Life)",
    sourceDocuments: [
      "TRL_Main Brochure_V26.pdf",
      "TRL_10 & 11 Marketing collaterals_mar_2026 1.pdf",
    ],
    marqueeUSP: "The Right Life | 100+ acre township",
    detailGroups: [
      {
        title: "Location",
        items: [
          "Residential. Commercial. Sports. Retail. Whitefield-Sarjapur Road.",
          "Situated at the junction of Whitefield, Sarjapur road and the ORR",
          "Just 800 metres from the upcoming Dommasandra metro station",
          "Live right next to everything",
        ],
      },
      {
        title: "Project Type",
        items: [
          "Discover Bangalore’s largest child-centric integrated township.",
          "An integrated township built for the future Bengaluru",
          "Residential",
          "Commercial",
          "Retail Zone",
          "Sports",
        ],
      },
      {
        title: "Unit Types",
        items: [
          "1800 to 4942 SFT homes",
          "Series 1 (Towers 1 to 3)",
          "3 BHK + 3T",
          "SBA",
          "2067 SFT",
          "RERA Carpet",
          "1181.89 SFT",
          "Utility + Balcony Area",
          "299.46 SFT",
          "Facing",
          "West",
          "Series 2 (Towers 1 to 3)",
          "3 BHK + 3T",
          "SBA",
          "1953 SFT",
          "RERA Carpet",
          "1182.53 SFT",
          "Series 3 (Tower10)",
          "2BHK+2T",
          "SBA",
          "1246SQFT",
          "RERA Carpet",
          "811SQFT",
          "BalconyArea",
          "44SQFT",
          "Facing",
          "EAST",
          "Series 5 (Tower 10)",
          "3BHK+3T",
          "SBA",
          "1682SQFT",
          "RERACarpet",
          "1072SQFT",
          "Series 10 ( Tower 10)",
          "3BHK+3T",
          "SBA",
          "1688SQFT",
          "RERACarpet",
          "1085SQFT",
          "Series 2& 4 (Tower 10)",
          "1BHK+ 1T",
          "RERACarpet",
          "632SQFT",
          "BalconyArea",
          "44SQFT",
        ],
      },
      {
        title: "Amenities",
        items: [
          "Cricket nets",
          "Basketball court",
          "Football ground",
          "Tennis, padel & pickleball courts",
          "Badminton & squash courts",
          "Swimming pool",
          "Skating park",
          "Gym",
          "Yoga studios",
          "Golf putting area",
          "High-impact studio",
          "Tournament-standard facilities",
          "A gym and yoga deck on the refuge floor of every tower",
        ],
      },
      {
        title: "Features",
        items: [
          "100+ acre township",
          "40+ child-centric features",
          "13 acre scenic lake nearby",
          "100+ unique experiences",
          "40+ top schools nearby",
          "3.5 lakh SFT of clubhouses",
          "84+ acres open area",
          "6.5 acres sports facilities",
          "84% open areas, a rare urban luxury!",
        ],
      },
      {
        title: "Proximity",
        items: [
          "Wipro - 7.8km",
          "RGA Tech Park - 8.6km",
          "Forum Mall - 5km",
          "Inventure Academy - Right next to The Right Life",
          "United World Academy - Right next to The Right Life",
          "Greenwood High International School - 100m",
          "TISB – 850m",
        ],
      },
    ],
  },
  {
    name: "Godrej Lakeside Orchards",
    sourceDocuments: [],
    marqueeUSP: "Godrej Lakeside Orchards | 2BHK to 4.5BHK",
    overview: {
      propertyName: "Godrej Lakeside Orchards",
      location: "Sarjapur Road in Bengaluru",
      configurations: "2BHK to 4.5BHK",
    },
    detailGroups: [
      {
        title: "Title",
        items: ["Godrej Lakeside Orchards"],
      },
      {
        title: "Description",
        items: [],
      },
      {
        title: "Advantages",
        items: [],
      },
      {
        title: "Project Overview",
        items: [
          "Property Name | Godrej Lakeside Orchards",
          "Location | Sarjapur Road in Bengaluru",
          "Configurations | 2BHK to 4.5BHK",
        ],
      },
      {
        title: "Specifications",
        items: [],
      },
      {
        title: "Amenities",
        items: [],
      },
      {
        title: "Price List",
        items: ["Configurations | 2BHK to 4.5BHK"],
      },
      {
        title: "About Builder",
        items: [],
      },
      {
        title: "FAQ",
        items: [],
      },
    ],
  },
];

export const rotatingProjectHighlights = [
  "Birla Evara | Total Indoor Amenities area 58,247 Sq Ft.",
  "Nambiar District 25 | 7 acre clubhouse.",
  "SSVR Meridian | 119 UNITS",
  "The Sports Province | 2, 3 & 3.5 BHK homes starting at ₹1.3 Cr*",
  "MEDA East Winds | 8.25 acres",
  "East Park Residences | 20 percent ground coverage, leaving 80 percent open areas",
  "The Right Life | 100+ acre township",
  "Godrej Lakeside Orchards | 2BHK to 4.5BHK",
];
